Nodel: nodel::Object
nodel::Object
#include <Object.h>
Detailed Description
Nodel dynamic object.
Like Python objects, an Object is a reference to its backing data. The assignment operator does not copy the backing data - it copies the reference.
Objects are garbage collected.
Objects have a reference count and are not thread-safe. However an Object can be accessed from different threads synchronously.
The backing data is one of the following types:
nil (similar to "None" in Python)
boolean
integer (64-bit, as defined in nodel/support/types.h)
unsigned integer (64-bit, as defined in nodel/support/types.h)
floating point (64-bit, as defined in nodel/support/types.h)
string (may represent either text, or binary data)
list (a recursive list of Objects)
ordered map (an insertion ordered map, Key -> Object)
sorted map (a sorted map, Key -> Object)
The NIL, BOOL, INT, UINT and FLOAT data types are stored in the Object by-value. Objects containing these types do not have a reference count, or a parent.
The get, set, and del methods can be used for both lists and maps.
When working with a list, Key instances are integers. Lists and maps are referred to collectively as "containers".
In general the get and set methods are faster than the subscript operator. However a chain of subscript operators will result in a single call to get or set with an OPath instance, which can be optimized by a DataSource implementation.
The get, set, and del methods do not accept const char* strings, since this would be the most common usage, and (to my knowledge) can't be optimized since it's not possible to know whether a const char* is a read-only literal.
Compiling with NODEL_ARCH=32 on 32-bit architectures will reduce the size of Object instances from 16-bytes to 8-bytes.
Examples
examples/find.cpp, and examples/rocksdb.cpp.
Definition at line 138 of file Object.h.
Public Types
enum ReprIX {
EMPTY ,
NIL ,
BOOL ,
INT ,
UINT ,
FLOAT ,
STR ,
LIST ,
SMAP ,
OMAP ,
DSRC ,
DEL ,
INVALID = 31
}
Public Member Functions
Object ()
Create an empty Object.
Object (nil_t)
Create a reference to nil.
Object (const String &str)
Copy string.
Object (String &&str)
Move string.
Object (const StringView &sv)
Copy string view.
Object (const char *v)
Copy plain string.
Object (bool v)
From boolean value.
Object (is_like_Float auto v)
From float value.
Object (is_like_Int auto v)
From signed integer value.
Object (is_like_UInt auto v)
From unsigned integer value.
Object (DataSourcePtr ptr)
Create an Object with a DataSource (Use nodel::bind, instead)
Object (const ObjectList &)
Copy Objects from container.
Object (const SortedMap &)
Copy Key/Object pairs from container.
Object (const OrderedMap &)
Copy Key/Object pairs from container.
Object (ObjectList &&)
Move Key/Object pairs from container.
Object (SortedMap &&)
Move Key/Object pairs from container.
Object (OrderedMap &&)
Move Key/Object pairs from container.
Object (const Key &)
Object (Key &&)
Object (ReprIX type)
Construct with a new, default value for the specified data type.
Object (const Subscript< Key > &sub)
Implicit conversion of Subscript<Key>
Object (const Subscript< OPath > &sub)
Implicit conversion of Subscript<OPath>
Object (const Object &other)
Object (Object &&other)
ReprIX type () const
std::string_view type_name () const
Returns a readable name for the type of the Object.
Object root () const
Returns the root container.
Object parent () const
Returns the parent container which holds this Object.
KeyRange iter_keys () const
Returns a range-like object over container Keys.
ItemRange iter_items () const
Returns a range-like object over container std::pair<Key, Object>
ValueRange iter_values () const
Returns a range-like object over container Objects.
KeyRange iter_keys (const Slice &) const
Returns a range-like object over a slice of container.
ItemRange iter_items (const Slice &) const
Returns a range-like object over a slice of container.
ValueRange iter_values (const Slice &) const
Returns a range-like object over a slice of container.
LineRange iter_line () const
Iterate this Object and its ancestors.
TreeRange< Object, NoPredicate, NoPredicate > iter_tree () const
Iterate the subtree rooted on this Object.
template<typename VisitPred >
TreeRange< Object, Predicate, NoPredicate > iter_tree (VisitPred &&) const
Iterate the subtree rooted on this Object and filtered by a predicate.
template<typename EnterPred >
TreeRange< Object, NoPredicate, Predicate > iter_tree_if (EnterPred &&) const
Iterate selected branches of the subtree rooted on this Object.
template<typename VisitPred , typename EnterPred >
TreeRange< Object, Predicate, Predicate > iter_tree_if (VisitPred &&, EnterPred &&) const
Iterate with both a "visit" predicate and an "enter" predicate.
size_t size () const
Returns the size of the string or container.
const Key key () const
Get the key associated with this Object.
const Key key_of (const Object &) const
Get the key associated with the specified Object.
OPath path () const
Get the path from the root to this Object.
OPath path (const Object &root) const
Get the path from the specified ancestor to this Object.
template<typename T >
bool is_type () const
Check the type of the stored data.
template<typename V >
void visit (V &&visitor) const
Similar to the std::visit function.
template<typename T >
requires is_byvalue<T>
T as () const
Get the stored data iff the data has the specified numeric type.
template<typename T >
requires std::is_same<T, String>::value
const T & as () const
Get the stored data iff the data has the specified numeric type.
template<typename T >
requires is_byvalue<T>
T & as ()
Get the stored data iff the data has the specified numeric type.
template<typename T >
requires std::is_same<T, String>::value
T & as ()
template<typename T >
requires std::is_same<T, ObjectList>::value
T as () const
bool is_empty () const
Test if this Object is an empty reference.
bool is_deleted () const
Test if this Object has been deleted from a sparse DataSource.
bool is_valid () const
Test if this Object was successfully loaded into memory.
template<typename T >
T cast () const
Key to_key () const
Creates a Key with the same value as this Object, if possible.
String to_str () const
Create a string representation of the stored data type.
String to_json () const
void to_json (std::ostream &) const
Object get (is_like_Int auto) const
Get the value of a key from a container or string.
Object get (const Key &) const
Get the value of a key from a container or string.
Object get (const OPath &) const
This method is equivalent to calling OPath::lookup(const Object&).
ObjectList get (const Slice &) const
Intended for small intervals - use Object::iter_values(), otherwise.
Object set (const Object &)
Overwrite (clobber) the stored data type of this Object.
Object set (const Key &, const Object &)
Set the value of a key in this container.
Object set (const OPath &, const Object &)
Equivalent to calling OPath::create(const Object&, const Object&)
void set (const Slice &, const ObjectList &)
Set a slice of values.
Object insert (const Key &, const Object &)
Insert a value at the specified key in the container.
void del (const Key &)
Delete the value of a key.
void del (const OPath &)
Delete the leaf of a path.
void del (const Slice &)
void del_from_parent ()
Delete this Object from its parent container.
void clear ()
Clear the elements, or string content, of this Object.
Subscript< Key > operator[] (const Key &key)
Subscript< OPath > operator[] (const OPath &path)
bool operator== (const Object &) const
bool operator== (nil_t) const
std::partial_ordering operator<=> (const Object &) const
Oid id () const
bool is (const Object &other) const
Object copy () const
refcnt_t ref_count () const
void inc_ref_count () const
void dec_ref_count () const
void release ()
void refer_to (const Object &)
Object & operator= (const Object &other)
Object & operator= (Object &&other)
template<class DataSourceType >
DataSourceType * data_source () const
void needs_saving ()
Mark this Object as having been updated.
void save ()
Save changes made in the subtree.
void reset ()
void reset_key (const Key &)
void refresh ()
void refresh_key (const Key &)
template<>
bool cast () const
Cast the data type stored in this Object to a bool.
template<>
Int cast () const
Cast the data type stored in this Object to a signed integer.
template<>
UInt cast () const
Cast the data type stored in this Object to a signed integer.
template<>
Float cast () const
Cast the data type stored in this Object to a signed integer.
Static Public Member Functions
static std::string_view type_name (uint8_t repr_ix)
Returns a text description of the type enumeration.
static WrongType wrong_type (uint8_t actual)
static WrongType wrong_type (uint8_t actual, uint8_t expected)
static EmptyReference empty_reference ()
Static Public Attributes
static constexpr refcnt_t no_ref_count = std::numeric_limits<refcnt_t>::max()
Indicates an object with a data type that is not reference counted.
Protected Member Functions
void map_set_slice (SortedMap &map, const Slice &slice, const ObjectList &in_vals)
Object list_set (const Key &key, const Object &in_val)
Object dsrc_read () const
void set_parent (const Object &parent) const
For internal use only.
void clear_parent () const
For internal use only.
void weak_refer_to (const Object &)
For internal use only.
Static Protected Member Functions
static bool norm_index (is_like_Int auto &index, UInt size)
Protected Attributes
Repr m_repr
Fields m_fields
Member Enumeration Documentation
ReprIX
enum nodel::Object::ReprIX
Definition at line 145 of file Object.h.
Constructor & Destructor Documentation
Object() [1/24]
nodel::Object::Object ()
Create an empty Object.
Empty objects behave like references that don't point to anything. Any attempt to access data will result in an EmptyReference exception being thrown.
Definition at line 266 of file Object.h.
Referenced by nodel::DataSource::read_key().
Object() [2/24]
nodel::Object::Object (nil_t)
Create a reference to nil.
Definition at line 269 of file Object.h.
Object() [3/24]
nodel::Object::Object (const String & str)
Copy string.
Definition at line 271 of file Object.h.
Referenced by Object().
Object() [4/24]
nodel::Object::Object (String && str)
Move string.
Definition at line 273 of file Object.h.
Object() [5/24]
nodel::Object::Object (const StringView & sv)
Copy string view.
Definition at line 275 of file Object.h.
Object() [6/24]
nodel::Object::Object (const char * v)
Copy plain string.
Definition at line 277 of file Object.h.
Object() [7/24]
nodel::Object::Object (bool v)
From boolean value.
Definition at line 279 of file Object.h.
Object() [8/24]
nodel::Object::Object (is_like_Float auto v)
From float value.
Definition at line 281 of file Object.h.
Referenced by Object(), and Object().
Object() [9/24]
nodel::Object::Object (is_like_Int auto v)
From signed integer value.
Definition at line 283 of file Object.h.
Object() [10/24]
nodel::Object::Object (is_like_UInt auto v)
From unsigned integer value.
Definition at line 285 of file Object.h.
Object() [11/24]
nodel::Object::Object (DataSourcePtr ptr)
Create an Object with a DataSource (Use nodel::bind, instead)
This is a low-level interface. Prefer using one of the nodel::bind functions, so that you can take advantage of configuring the DataSource from a URI.
Definition at line 1163 of file Object.h.
Object() [12/24]
nodel::Object::Object (const ObjectList & list)
Copy Objects from container.
Definition at line 1166 of file Object.h.
Object() [13/24]
nodel::Object::Object (const SortedMap & map)
Copy Key/Object pairs from container.
Definition at line 1176 of file Object.h.
Object() [14/24]
nodel::Object::Object (const OrderedMap & map)
Copy Key/Object pairs from container.
Definition at line 1186 of file Object.h.
Object() [15/24]
nodel::Object::Object (ObjectList && list)
Move Key/Object pairs from container.
Definition at line 1196 of file Object.h.
Object() [16/24]
nodel::Object::Object (SortedMap && map)
Move Key/Object pairs from container.
Definition at line 1205 of file Object.h.
Object() [17/24]
nodel::Object::Object (OrderedMap && map)
Move Key/Object pairs from container.
Definition at line 1214 of file Object.h.
Object() [18/24]
nodel::Object::Object (const Key & key)
Definition at line 1223 of file Object.h.
Object() [19/24]
nodel::Object::Object (Key && key)
Definition at line 1240 of file Object.h.
Object() [20/24]
nodel::Object::Object (ReprIX type)
Construct with a new, default value for the specified data type.
Parameters
type The data type.
Definition at line 1257 of file Object.h.
Object() [21/24]
nodel::Object::Object (const Subscript< Key > & sub)
Implicit conversion of Subscript<Key>
Definition at line 3549 of file Object.h.
Object() [22/24]
nodel::Object::Object (const Subscript< OPath > & sub)
Implicit conversion of Subscript<OPath>
Definition at line 3550 of file Object.h.
Object() [23/24]
nodel::Object::Object (const Object & other)
Definition at line 1126 of file Object.h.
Object() [24/24]
nodel::Object::Object (Object && other)
Definition at line 1143 of file Object.h.
~Object()
nodel::Object::~Object ()
Definition at line 323 of file Object.h.
Member Function Documentation
type_name() [1/2]
static std::string_view nodel::Object::type_name (uint8_t repr_ix) static
Returns a text description of the type enumeration.
Parameters
repr_ix The value of the ReprIX enumeration.
Definition at line 238 of file Object.h.
type()
Object::ReprIX nodel::Object::type () const
Definition at line 1275 of file Object.h.
type_name() [2/2]
std::string_view nodel::Object::type_name () const
Returns a readable name for the type of the Object.
Definition at line 328 of file Object.h.
root()
Object nodel::Object::root () const
Returns the root container.
Definition at line 1284 of file Object.h.
parent()
Object nodel::Object::parent () const
Returns the parent container which holds this Object.
Definition at line 1296 of file Object.h.
Referenced by nodel::DataSource::bind(), nodel::OPath::is_leaf(), path(), and path().
iter_keys() [1/2]
KeyRange nodel::Object::iter_keys () const
Returns a range-like object over container Keys.
Examples
examples/rocksdb.cpp.
Definition at line 2045 of file Object.h.
iter_items() [1/2]
ItemRange nodel::Object::iter_items () const
Returns a range-like object over container std::pair<Key, Object>
Definition at line 2050 of file Object.h.
iter_values() [1/2]
ValueRange nodel::Object::iter_values () const
Returns a range-like object over container Objects.
Definition at line 2055 of file Object.h.
iter_keys() [2/2]
KeyRange nodel::Object::iter_keys (const Slice & slice) const
Returns a range-like object over a slice of container.
Definition at line 2060 of file Object.h.
iter_items() [2/2]
ItemRange nodel::Object::iter_items (const Slice & slice) const
Returns a range-like object over a slice of container.
Definition at line 2065 of file Object.h.
iter_values() [2/2]
ValueRange nodel::Object::iter_values (const Slice & slice) const
Returns a range-like object over a slice of container.
Definition at line 2070 of file Object.h.
Referenced by get().
iter_line()
LineRange nodel::Object::iter_line () const
Iterate this Object and its ancestors.
Definition at line 2814 of file Object.h.
iter_tree() [1/2]
Object::TreeRange< Object, NoPredicate, NoPredicate > nodel::Object::iter_tree () const
Iterate the subtree rooted on this Object.
Returns
Returns a range-like object.
Definition at line 2924 of file Object.h.
iter_tree() [2/2]
template<typename VisitPred > Object::TreeRange< Object, Predicate, NoPredicate > nodel::Object::iter_tree (VisitPred && visit_pred) const
Iterate the subtree rooted on this Object and filtered by a predicate.
Template Parameters
VisitPred Any function-like type (lambdas)
Parameters
visit_pred A predicate function that is called with each iterated Object.
Returns
Returns a range-like object.
Definition at line 2933 of file Object.h.
iter_tree_if() [1/2]
template<typename EnterPred > Object::TreeRange< Object, NoPredicate, Predicate > nodel::Object::iter_tree_if (EnterPred && enter_pred) const
Iterate selected branches of the subtree rooted on this Object.
Template Parameters
EnterPred Any function-like type (lambdas)
Parameters
enter_pred A predicate function that determines whether the algorithm descends into a container Object. Unlike the "visit" predicate, the "enter" predicate controls which Objects in the subtree are entered (descended into). This is useful for improving performance, as well as controlling whether Objects with DataSources are loaded into memory.
Returns
Returns a range-like object.
Examples
examples/find.cpp.
Definition at line 2946 of file Object.h.
iter_tree_if() [2/2]
template<typename VisitPred , typename EnterPred > Object::TreeRange< Object, Predicate, Predicate > nodel::Object::iter_tree_if (VisitPred && visit_pred, EnterPred && enter_pred) const
Iterate with both a "visit" predicate and an "enter" predicate.
Template Parameters
VisitPred Any function-like type (lambdas)
EnterPred Any function-like type (lambdas)
Parameters
visit_pred A predicate function that is called with each iterated Object.
enter_pred A predicate function that determines whether the algorithm descends into a container Object.
Returns
Returns a range-like object.
Definition at line 2958 of file Object.h.
size()
size_t nodel::Object::size () const
Returns the size of the string or container.
Returns
Returns the size of the string or container, or 0 for other types.
Definition at line 2027 of file Object.h.
key()
const Key nodel::Object::key () const
Get the key associated with this Object.
If this Object has a parent then this method returns the key by which you can access this Object within its parent.
If this Object does not have a parent, then nil is returned.
Returns
Returns nil or the key.
Definition at line 1496 of file Object.h.
key_of()
const Key nodel::Object::key_of (const Object & obj) const
Get the key associated with the specified Object.
Parameters
obj The Object.
Returns
Returns nil or the key.
Exceptions
WrongType
EmptyReference
Definition at line 1506 of file Object.h.
Referenced by nodel::DataSource::bind(), path(), and path().
path() [1/2]
OPath nodel::Object::path () const
Get the path from the root to this Object.
Get an OPath instance that would yield this Object from the following expression: this->root().get(path)
If the Object does not have a parent then an empty path is returned.
Returns
Returns a (possibly empty) OPath instance.
See also
Object::get(const OPath&)
Object::set(const OPath&, const Object&)
Definition at line 741 of file Object.h.
Referenced by path().
path() [2/2]
OPath nodel::Object::path (const Object & root) const
Get the path from the specified ancestor to this Object.
Parameters
root An ancestor of this Object.
This method is similar to the Object::path() method except that you can specify an ancestor other than the root of the tree.
If root is not an ancestor of this Object then it is ignored and the root of the tree is used, instead.
Returns
Returns a (possibly empty) OPath instance.
See also
Object::get(const OPath&)
Object::set(const OPath&, const Object&)
Definition at line 764 of file Object.h.
is_type()
template<typename T > bool nodel::Object::is_type () const
Check the type of the stored data.
Template Parameters
T The type to test.
If this Object has a DataSource then it may be necessary to load some or all of the data to determine the type of Object. For example, since a JSON file may contain different types, it's necessary to load at least enough of the beginning of the JSON data to determine the type.
Returns
Returns true if the stored data has the specified type
Definition at line 1553 of file Object.h.
visit()
template<typename V > void nodel::Object::visit (V && visitor) const
Similar to the std::visit function.
Template Parameters
V The type of the visitor function
Parameters
visitor The visitor.
If the Object::is_empty method would return true then calling this method will throw an EmptyReference exception.
Definition at line 1314 of file Object.h.
as() [1/3]
template<typename T > requires is_byvalue<T> T nodel::Object::as () const
Get the stored data iff the data has the specified numeric type.
Get a copy of the elements in this list Object.
Template Parameters
T One of the supported numeric data types
The supported data types are: bool, Int, UInt, Float
Returns
Returns a copy of the stored data type
Exceptions
Throws a WrongType exception if the stored data type does not match
Template Parameters
T ObjectList This method returns a copy of the Objects in the list to prevent untracked modifications that might violate invariants.
Returns
Returns a copy of the list.
Definition at line 1334 of file Object.h.
as() [2/3]
template<typename T > requires std::is_same<T, String>::value const T & nodel::Object::as () const
Get the stored data iff the data has the specified numeric type.
Template Parameters
T String
This overload of the method is for String
Returns
Returns a const reference to the stored data type
Exceptions
Throws a WrongType exception if the stored data type does not match
Definition at line 1346 of file Object.h.
as() [3/3]
template<typename T > requires is_byvalue<T> T & nodel::Object::as ()
Get the stored data iff the data has the specified numeric type.
Template Parameters
T One of the supported numeric data types
The supported data types are: bool, Int, UInt, Float
Returns
Returns a reference to the stored data type
Exceptions
Throws a WrongType exception if the stored data type does not match
Template Parameters
T String
This overload of the method is for String
Note
If this Object has a DataSource and you modify the string data returned by this method, then you must call Object::needs_saving to set the unsaved flag, before call Object::save.
Returns
Returns a mutable reference to the String data
Exceptions
Throws a WrongType exception if the stored data type does not match
Definition at line 1358 of file Object.h.
is_empty()
bool nodel::Object::is_empty () const
Test if this Object is an empty reference.
An Object is an empty reference if it was never assigned a value.
Default constructed Object instances are empty references.
Calling Object::release will result in an empty reference.
Returns
Returns true if the Object is an empty reference.
Definition at line 1589 of file Object.h.
is_deleted()
bool nodel::Object::is_deleted () const
Test if this Object has been deleted from a sparse DataSource.
Sparse DataSource implementations load keys individually, so a special data type is reserved to indicate that a key has been deleted.
This method is only useful for a sparse DataSource implementation.
Returns
Returns true if the key associated with this Object was deleted.
Definition at line 1599 of file Object.h.
is_valid()
bool nodel::Object::is_valid () const
Test if this Object was successfully loaded into memory.
An Object containing a DataSource configured not to throw exceptions will be marked invalid if a load operation fails.
Use this method to verify that a load operation was successful whenever the DataSource is configured not to throw exceptions.
Returns
Returns true if the Object was successfully loaded, or if the Object does not have a DataSource.
Definition at line 1611 of file Object.h.
to_key()
Key nodel::Object::to_key () const
Creates a Key with the same value as this Object, if possible.
The following types can be cast to a bool: NIL, BOOL, INT, UINT, FLOAT, STR or DataSources with one of those types.
Exceptions
WrongType
EmptyReference
Definition at line 1708 of file Object.h.
to_str()
String nodel::Object::to_str () const
Create a string representation of the stored data type.
NIL is returned as, "nil"
BOOL is returned as, "true" or "false"
INT, UINT and FLOAT are converted to strings with maximum precision
Containers are converted to JSON strings
A DataSource is converted based on the data type it loads.
Exceptions
WrongType
EmptyReference
Definition at line 1566 of file Object.h.
to_json() [1/2]
String nodel::Object::to_json () const
Definition at line 2522 of file Object.h.
to_json() [2/2]
void nodel::Object::to_json (std::ostream & os) const
Definition at line 2529 of file Object.h.
get() [1/4]
Object nodel::Object::get (is_like_Int auto index) const
Get the value of a key from a container or string.
Parameters
index An integer key.
This method may provide slightly faster access to list elements by avoiding the creation of a temporary Key.
If the key is less than zero, the size of the container is first added to the key.
Exceptions
WrongType
EmptyReference
Definition at line 1738 of file Object.h.
get() [2/4]
Object nodel::Object::get (const Key & key) const
Get the value of a key from a container or string.
Parameters
key The key to lookup.
If the key is less than zero, the size of the container is first added to the key.
If the stored data type is a list then the key must be convertible to a signed integer. The key is used to index the list.
If the stored data type is a map then any key type may be used.
If the stored data type is NIL then NIL is returned.
Exceptions
EmptyReference
Definition at line 1761 of file Object.h.
get() [3/4]
Object nodel::Object::get (const OPath & path) const
This method is equivalent to calling OPath::lookup(const Object&).
Parameters
path The path whose leaf value will be returned.
Exceptions
WrongType
EmptyReference
Definition at line 1793 of file Object.h.
get() [4/4]
ObjectList nodel::Object::get (const Slice & slice) const
Intended for small intervals - use Object::iter_values(), otherwise.
Todo
Consider whether slicing a map should slice keys or slice the list of map items currently it slices keys, which is useful when a map is used to represent a sparse list
Parameters
slice A slice of elements to retrieve.
Note
If this Object is a list or map then copies of the values will be returned. Use Object::iter_values() when the values that will be returned may be strings, lists or maps.
Returns
Returns a list Object with the (possibly copied) elements.
Exceptions
WrongType
EmptyReference
Definition at line 2086 of file Object.h.
set() [1/4]
Object nodel::Object::set (const Object & value)
Overwrite (clobber) the stored data type of this Object.
Parameters
value The value to be assigned.
If this Object has a parent then this method is equivalent to this->parent().set(this->key(), value) - that is, it replaces this Object in the parent container.
Otherwise, this method is equivalent to calling the assignment operator.
Examples
examples/rocksdb.cpp.
Definition at line 1804 of file Object.h.
set() [2/4]
Object nodel::Object::set (const Key & key, const Object & in_val)
Set the value of a key in this container.
Parameters
key The key to be assigned.
in_val The value to be assigned to the key.
If in_val already has a parent then it a copy is created and the copy is assigned to the key. An Object can only have one parent. Call Object::del_from_parent() to avoid the copy.
If this Object is a list and the key is negative, the size of the list is added to the key. The list elements are consecutively replaced.
See also
Object::insert(const Key&, const Object&)
Returns
Returns the Object that was actually inserted, which may be a copy.
Exceptions
WrongType
EmptyReference
Definition at line 1865 of file Object.h.
Referenced by nodel::DataSource::bind().
set() [3/4]
Object nodel::Object::set (const OPath & path, const Object & in_val)
Equivalent to calling OPath::create(const Object&, const Object&)
Note
All the same rules apply as for the other Object::set methods.
Returns
Returns the Object that was actually inserted, which may be a copy.
Exceptions
WrongType
EmptyReference
Definition at line 1908 of file Object.h.
set() [4/4]
void nodel::Object::set (const Slice & slice, const ObjectList & in_vals)
Set a slice of values.
Parameters
slice An interval (slice) of keys.
in_vals The values to be assigned.
If the number of values in in_vals is greater than the elements addressed by slice, then the extra elements in in_vals are ignored.
If the number of values in in_vals is less than the elements addressed by by slice, then the extra elements address by the slice are removed.
This method can be used with an sorted map Object to behave like a sparse array. However, the start and stop must be explicitly specified in the slice. If any of the slice parameters are negative, a std::out_of_range exception is thrown.
Exceptions
std::out_of_range
WrongType
EmptyReference
Definition at line 2113 of file Object.h.
insert()
Object nodel::Object::insert (const Key & key, const Object & in_val)
Insert a value at the specified key in the container.
This method is identical to Object::set(const Key&, const Object&) for maps.
For lists, this method inserts, instead of replaces, the elements.
Returns
Returns the Object that was actually inserted, which may be a copy.
Exceptions
WrongType
EmptyReference
Definition at line 1920 of file Object.h.
del() [1/3]
void nodel::Object::del (const Key & key)
Delete the value of a key.
Parameters
key The key to be deleted.
If this Object is a list and the key is negative, the size of the list is added to the key.
If this Object is a string then a WrongType exception is thrown. Use Object::as<String>(), instead.
Exceptions
WrongType
EmptyReference
Definition at line 1946 of file Object.h.
del() [2/3]
void nodel::Object::del (const OPath & path)
Delete the leaf of a path.
Exceptions
WrongType
EmptyReference
Definition at line 1992 of file Object.h.
del() [3/3]
void nodel::Object::del (const Slice & slice)
Definition at line 2196 of file Object.h.
del_from_parent()
void nodel::Object::del_from_parent ()
Delete this Object from its parent container.
Exceptions
WrongType
EmptyReference
Definition at line 2004 of file Object.h.
clear()
void nodel::Object::clear ()
Clear the elements, or string content, of this Object.
Definition at line 2012 of file Object.h.
operator[]() [1/2]
Object::Subscript< Key > nodel::Object::operator[] (const Key & key)
Definition at line 3552 of file Object.h.
operator[]() [2/2]
Object::Subscript< OPath > nodel::Object::operator[] (const OPath & path)
Definition at line 3553 of file Object.h.
operator==() [1/2]
bool nodel::Object::operator== (const Object & obj) const
Definition at line 2227 of file Object.h.
operator==() [2/2]
bool nodel::Object::operator== (nil_t) const
Definition at line 2305 of file Object.h.
operator<=>()
std::partial_ordering nodel::Object::operator<=> (const Object & obj) const
Definition at line 2310 of file Object.h.
id()
Oid nodel::Object::id () const
Definition at line 2559 of file Object.h.
is()
bool nodel::Object::is (const Object & other) const
Definition at line 2578 of file Object.h.
copy()
Object nodel::Object::copy () const
Definition at line 2598 of file Object.h.
ref_count()
refcnt_t nodel::Object::ref_count () const
Definition at line 2617 of file Object.h.
inc_ref_count()
void nodel::Object::inc_ref_count () const
Definition at line 2630 of file Object.h.
dec_ref_count()
void nodel::Object::dec_ref_count () const
Definition at line 2644 of file Object.h.
release()
void nodel::Object::release ()
Definition at line 2698 of file Object.h.
refer_to()
void nodel::Object::refer_to (const Object & other)
Definition at line 1397 of file Object.h.
operator=() [1/2]
Object & nodel::Object::operator= (const Object & other)
Definition at line 2705 of file Object.h.
operator=() [2/2]
Object & nodel::Object::operator= (Object && other)
Definition at line 2746 of file Object.h.
data_source()
template<class DataSourceType > DataSourceType * nodel::Object::data_source () const
Definition at line 2771 of file Object.h.
needs_saving()
void nodel::Object::needs_saving ()
Mark this Object as having been updated.
If this Object has a DataSoource then it is flagged as having been updated such that it will be saved on the next call to Object::save. This is only necessary when string data is modified by reference by calling Object::as<T>
Definition at line 2968 of file Object.h.
save()
void nodel::Object::save ()
Save changes made in the subtree.
This method visits Objects with a DataSource in the subtree of this Object that have been loaded into memory and calls the DataSource::save method.
This method will not trigger a DataSource to load.
Use the Object::reset or Object::reset_key methods to discard changes before calling this method.
Only Objects that whose unsaved bit is set will be saved. The unsaved bit is set whenever a method is called that modifies the Object's data.
Use the Object::needs_saving method to set the unsaved bit, if you modify string data by reference, as returned by the Object::as<String> method.
Examples
examples/rocksdb.cpp.
Definition at line 2985 of file Object.h.
reset()
void nodel::Object::reset ()
Examples
examples/rocksdb.cpp.
Definition at line 3022 of file Object.h.
reset_key()
void nodel::Object::reset_key (const Key & key)
Definition at line 3028 of file Object.h.
refresh()
void nodel::Object::refresh ()
Definition at line 3034 of file Object.h.
refresh_key()
void nodel::Object::refresh_key (const Key & key)
Definition at line 3040 of file Object.h.
wrong_type() [1/2]
static WrongType nodel::Object::wrong_type (uint8_t actual) static
Definition at line 440 of file Object.h.
wrong_type() [2/2]
static WrongType nodel::Object::wrong_type (uint8_t actual, uint8_t expected) static
Definition at line 441 of file Object.h.
empty_reference()
static EmptyReference nodel::Object::empty_reference () static
Definition at line 442 of file Object.h.
norm_index()
bool nodel::Object::norm_index (is_like_Int auto & index, UInt size) static protected
Definition at line 1723 of file Object.h.
list_set()
Object nodel::Object::list_set (const Key & key, const Object & in_val) protected
Definition at line 1836 of file Object.h.
dsrc_read()
Object nodel::Object::dsrc_read () const protected
Definition at line 1392 of file Object.h.
set_parent()
void nodel::Object::set_parent (const Object & parent) const protected
For internal use only.
Definition at line 1425 of file Object.h.
clear_parent()
void nodel::Object::clear_parent () const protected
For internal use only.
Definition at line 1459 of file Object.h.
Referenced by nodel::DataSource::bind().
weak_refer_to()
void nodel::Object::weak_refer_to (const Object & other) protected
For internal use only.
Definition at line 1403 of file Object.h.
cast() [1/4]
template<> bool nodel::Object::cast () const
Cast the data type stored in this Object to a bool.
Casting a container to bool returns true if the size > 0.
Casting an Object with a DataSource is equivalent to casting the loaded value.
Exceptions
WrongType
EmptyReference
Definition at line 1626 of file Object.h.
cast() [2/4]
template<> Int nodel::Object::cast () const
Cast the data type stored in this Object to a signed integer.
The following types can be cast to a bool: NIL, BOOL, INT, UINT, FLOAT, STR or DataSources with one of those types.
Exceptions
WrongType
EmptyReference
Definition at line 1649 of file Object.h.
cast() [3/4]
template<> UInt nodel::Object::cast () const
Cast the data type stored in this Object to a signed integer.
The following types can be cast to a bool: NIL, BOOL, INT, UINT, FLOAT, STR or DataSources with one of those types.
Exceptions
WrongType
EmptyReference
Definition at line 1669 of file Object.h.
cast() [4/4]
template<> Float nodel::Object::cast () const
Cast the data type stored in this Object to a signed integer.
The following types can be cast to a bool: NIL, BOOL, INT, UINT, FLOAT, STR or DataSources with one of those types.
Exceptions
WrongType
EmptyReference
Definition at line 1688 of file Object.h.
Member Data Documentation
no_ref_count
constexpr refcnt_t nodel::Object::no_ref_count = std::numeric_limits<refcnt_t>::max() static constexpr
Indicates an object with a data type that is not reference counted.
See also
See Object::ref_count method.
Definition at line 260 of file Object.h.
m_repr
Repr nodel::Object::m_repr protected
Definition at line 456 of file Object.h.
m_fields
Fields nodel::Object::m_fields protected
Definition at line 457 of file Object.h.
The documentation for this class was generated from the following file:
include/nodel/core/Object.h