Nodel: nodel::filesystem::SubDirectory
nodel::filesystem::SubDirectory
DataSource for filesystem directories.
#include <Directory.hxx>
Public Member Functions
SubDirectory (Origin origin)
DataSource * new_instance (const Object &target, Origin origin) const override
Create a new instance of this DataSource.
void configure (const Object &uri) override
Configure this DataSource from a URI.
void read_type (const Object &) override
Determine the type of data in external storage.
void read (const Object &target) override
Read all data from external storage.
void write (const Object &target, const Object &) override
Write data to external storage.
void set_registry (Ref< Registry > r_reg)
Ref< Registry > registry () const
Public Member Functions inherited from nodel::DataSource
DataSource (Kind kind, Origin origin, Multilevel multi_level=Multilevel::NO)
DataSource (Kind kind, ReprIX repr_ix, Origin origin, Multilevel multi_level=Multilevel::NO)
const Object & get_cached (const Object &target) const
size_t size (const Object &target)
Object get (const Object &target, const Key &key)
Options options () const
void set_options (Options options)
Mode mode () const
void set_mode (Mode mode)
Mode resolve_mode () const
bool is_fully_cached () const
bool is_sparse () const
bool is_multi_level () const
void report_read_error (std::string &&error)
void report_write_error (std::string &&error)
bool is_valid (const Object &target)
void bind (Object &obj)
Bind an object to a DataSource.
Protected Attributes
Ref< Registry > mr_registry
Additional Inherited Members
Public Types inherited from nodel::DataSource
enum class Kind {
SPARSE ,
COMPLETE
}
enum class Origin {
SOURCE ,
MEMORY
}
enum class Multilevel {
NO ,
YES
}
using ReprIX = Object::ReprIX
Protected Member Functions inherited from nodel::DataSource
virtual Object read_key (const Object &target, const Key &key)
Read the data for the specified key from external storage.
virtual void write_key (const Object &target, const Key &key, const Object &value)
Write data for the specified key to external storage.
virtual void delete_key (const Object &target, const Key &key)
Delete a key from external storage.
virtual void commit (const Object &target, const Object &data, const KeyList &del_keys)
Called just before the Object::save() method finishes.
void read_set (const Object &target, const Object &value)
void read_set (const Object &target, const Key &key, const Object &value)
void read_set (const Object &target, Key &&key, const Object &value)
void read_del (const Object &target, const Key &key)
virtual std::unique_ptr< KeyIterator > key_iter ()
virtual std::unique_ptr< ValueIterator > value_iter ()
virtual std::unique_ptr< ItemIterator > item_iter ()
virtual std::unique_ptr< KeyIterator > key_iter (const Slice &)
virtual std::unique_ptr< ValueIterator > value_iter (const Slice &)
virtual std::unique_ptr< ItemIterator > item_iter (const Slice &)
virtual void free_resources ()
Detailed Description
DataSource for filesystem directories.
Definition at line 28 of file Directory.hxx.
Constructor & Destructor Documentation
SubDirectory()
nodel::filesystem::SubDirectory::SubDirectory (Origin origin)
Definition at line 31 of file Directory.hxx.
Member Function Documentation
new_instance()
DataSource * nodel::filesystem::SubDirectory::new_instance (const Object & target, Origin origin) const override virtual
Create a new instance of this DataSource.
Parameters
target The target that will receive this DataSource
origin Whether data originates in memory, or from external storage
Returns
Returns a heap-allocated DataSource instance.
Implements nodel::DataSource.
Definition at line 33 of file Directory.hxx.
configure()
void nodel::filesystem::SubDirectory::configure (const Object & uri) override virtual
Configure this DataSource from a URI.
Parameters
uri A map containing the parts of the URI.
See also
nodel/core/uri.h.
Reimplemented from nodel::DataSource.
Definition at line 35 of file Directory.hxx.
References nodel::DataSource::configure().
Referenced by nodel::filesystem::Directory::configure().
read_type()
void nodel::filesystem::SubDirectory::read_type (const Object & target) override virtual
Determine the type of data in external storage.
Parameters
target The target holding this DataSource.
Implementations should override this method when the type of data in storage is dynamic.
Implementations should use metadata where possible to make this operation inexpensive. This method may be called in situations where the end-user does not want to incur the overhead of loading the data.
Reimplemented from nodel::DataSource.
Definition at line 37 of file Directory.hxx.
read()
void nodel::filesystem::SubDirectory::read (const Object & target) override virtual
Read all data from external storage.
Parameters
target The target holding this DataSource.
This method must be implemented by both complete and sparse DataSources, although end-users can easily avoided this flow with sparse DataSources.
Implementations call the read_set methods to populate the data.
Implements nodel::DataSource.
Definition at line 143 of file Directory.hxx.
References nodel::Object::path().
write()
void nodel::filesystem::SubDirectory::write (const Object & target, const Object & data) override virtual
Write data to external storage.
Parameters
target The target holding this DataSource.
data The data to be written.
Implements nodel::DataSource.
Definition at line 166 of file Directory.hxx.
References nodel::Object::get(), nodel::Object::iter_items(), nodel::Object::needs_saving(), and nodel::Object::to_str().
set_registry()
void nodel::filesystem::SubDirectory::set_registry (Ref< Registry > r_reg)
Definition at line 41 of file Directory.hxx.
registry()
Ref< Registry > nodel::filesystem::SubDirectory::registry () const
Definition at line 42 of file Directory.hxx.
Member Data Documentation
mr_registry
Ref<Registry> nodel::filesystem::SubDirectory::mr_registry protected
Definition at line 45 of file Directory.hxx.
The documentation for this class was generated from the following file:
nodel/filesystem/Directory.hxx