Nodel: nodel::kvdb::DB
nodel::kvdb::DB
A simple key/value store backed by RocksDB.
#include <DB.hxx>
Public Member Functions
DB (const std::filesystem::path &path, Origin origin)
DB (DataSource::Origin origin)
DB (const DB &)=delete
DB (DB &&)=delete
DB * operator= (const DB &)=delete
DB * operator= (DB &&)=delete
void set_db_options (::rocksdb::Options options)
void set_read_options (::rocksdb::ReadOptions options)
void set_write_options (::rocksdb::WriteOptions options)
DataSource * new_instance (const Object &target, Origin origin) const override
Create a new instance of this DataSource.
void configure (const Object &uri) override
Configure this DataSource from a URI.
void read_type (const Object &target) override
Determine the type of data in external storage.
void read (const Object &target) override
Read all data from external storage.
void write (const Object &, const Object &cache) override
Write data to external storage.
Object read_key (const Object &, const Key &k) override
Read the data for the specified key from external storage.
void write_key (const Object &, const Key &k, const Object &v) override
Write data for the specified key to external storage.
void commit (const Object &target, const Object &data, const KeyList &del_keys) override
Called just before the Object::save() method finishes.
std::unique_ptr< nodel::DataSource::KeyIterator > key_iter () override
std::unique_ptr< nodel::DataSource::ValueIterator > value_iter () override
std::unique_ptr< nodel::DataSource::ItemIterator > item_iter () override
std::unique_ptr< nodel::DataSource::KeyIterator > key_iter (const Slice &) override
std::unique_ptr< nodel::DataSource::ValueIterator > value_iter (const Slice &) override
std::unique_ptr< nodel::DataSource::ItemIterator > item_iter (const Slice &) override
Public Member Functions inherited from nodel::DataSource
DataSource (Kind kind, Origin origin, Multilevel multi_level=Multilevel::NO)
DataSource (Kind kind, ReprIX repr_ix, Origin origin, Multilevel multi_level=Multilevel::NO)
const Object & get_cached (const Object &target) const
size_t size (const Object &target)
Object get (const Object &target, const Key &key)
Options options () const
void set_options (Options options)
Mode mode () const
void set_mode (Mode mode)
Mode resolve_mode () const
bool is_fully_cached () const
bool is_sparse () const
bool is_multi_level () const
void report_read_error (std::string &&error)
void report_write_error (std::string &&error)
bool is_valid (const Object &target)
void bind (Object &obj)
Bind an object to a DataSource.
Additional Inherited Members
Public Types inherited from nodel::DataSource
enum class Kind {
SPARSE ,
COMPLETE
}
enum class Origin {
SOURCE ,
MEMORY
}
enum class Multilevel {
NO ,
YES
}
using ReprIX = Object::ReprIX
Protected Member Functions inherited from nodel::DataSource
virtual void delete_key (const Object &target, const Key &key)
Delete a key from external storage.
void read_set (const Object &target, const Object &value)
void read_set (const Object &target, const Key &key, const Object &value)
void read_set (const Object &target, Key &&key, const Object &value)
void read_del (const Object &target, const Key &key)
virtual void free_resources ()
Detailed Description
A simple key/value store backed by RocksDB.
Multiple objects may operate on the same DB, but no synchronization is provided. Use Object::refresh or Object::reset to synchronize one object after changes have been made to the DB.
Updates and deletes are batched together when Object::save is called, providing atomicity.
Definition at line 26 of file DB.hxx.
Constructor & Destructor Documentation
DB() [1/2]
nodel::kvdb::DB::DB (const std::filesystem::path & path, Origin origin)
Definition at line 116 of file DB.hxx.
DB() [2/2]
nodel::kvdb::DB::DB (DataSource::Origin origin)
Definition at line 30 of file DB.hxx.
~DB()
nodel::kvdb::DB::~DB ()
Definition at line 124 of file DB.hxx.
Member Function Documentation
set_db_options()
void nodel::kvdb::DB::set_db_options (::rocksdb::Options options)
Definition at line 38 of file DB.hxx.
set_read_options()
void nodel::kvdb::DB::set_read_options (::rocksdb::ReadOptions options)
Definition at line 39 of file DB.hxx.
set_write_options()
void nodel::kvdb::DB::set_write_options (::rocksdb::WriteOptions options)
Definition at line 40 of file DB.hxx.
new_instance()
DataSource * nodel::kvdb::DB::new_instance (const Object & target, Origin origin) const override virtual
Create a new instance of this DataSource.
Parameters
target The target that will receive this DataSource
origin Whether data originates in memory, or from external storage
Returns
Returns a heap-allocated DataSource instance.
Implements nodel::DataSource.
Definition at line 42 of file DB.hxx.
configure()
void nodel::kvdb::DB::configure (const Object & uri) override virtual
Configure this DataSource from a URI.
Parameters
uri A map containing the parts of the URI.
See also
nodel/core/uri.h.
Reimplemented from nodel::DataSource.
Definition at line 308 of file DB.hxx.
References nodel::DataSource::configure(), and nodel::Object::get().
read_type()
void nodel::kvdb::DB::read_type (const Object & target) override virtual
Determine the type of data in external storage.
Parameters
target The target holding this DataSource.
Implementations should override this method when the type of data in storage is dynamic.
Implementations should use metadata where possible to make this operation inexpensive. This method may be called in situations where the end-user does not want to incur the overhead of loading the data.
Reimplemented from nodel::DataSource.
Definition at line 48 of file DB.hxx.
read()
void nodel::kvdb::DB::read (const Object & target) override virtual
Read all data from external storage.
Parameters
target The target holding this DataSource.
This method must be implemented by both complete and sparse DataSources, although end-users can easily avoided this flow with sparse DataSources.
Implementations call the read_set methods to populate the data.
Implements nodel::DataSource.
Definition at line 318 of file DB.hxx.
write()
void nodel::kvdb::DB::write (const Object & target, const Object & data) override virtual
Write data to external storage.
Parameters
target The target holding this DataSource.
data The data to be written.
Implements nodel::DataSource.
Definition at line 341 of file DB.hxx.
read_key()
Object nodel::kvdb::DB::read_key (const Object & target, const Key & key) override virtual
Read the data for the specified key from external storage.
Parameters
target The target holding this DataSource.
key The key to read.
sparse implementations must override this method.
Implementations call the read_set methods to populate the data.
Returns
Returns the value of the key, or nil.
Reimplemented from nodel::DataSource.
Definition at line 346 of file DB.hxx.
write_key()
void nodel::kvdb::DB::write_key (const Object & target, const Key & key, const Object & value) override virtual
Write data for the specified key to external storage.
Parameters
target The target holding this DataSource.
key The key to write.
value The value of the key.
sparse implementations must override this method.
Reimplemented from nodel::DataSource.
Definition at line 367 of file DB.hxx.
commit()
void nodel::kvdb::DB::commit (const Object & target, const Object & data, const KeyList & del_keys) override virtual
Called just before the Object::save() method finishes.
Parameters
target The target holding this DataSource.
data The memory representation of this DataSource.
del_keys The list of deleted keys.
This method is called at the end of the Object::save() flow to allow the implementation to batch updates.
This method is only called for sparse implementations.
Reimplemented from nodel::DataSource.
Definition at line 372 of file DB.hxx.
References nodel::Object::iter_items().
key_iter() [1/2]
std::unique_ptr< nodel::DataSource::KeyIterator > nodel::kvdb::DB::key_iter () override virtual
Reimplemented from nodel::DataSource.
Definition at line 221 of file DB.hxx.
value_iter() [1/2]
std::unique_ptr< nodel::DataSource::ValueIterator > nodel::kvdb::DB::value_iter () override virtual
Reimplemented from nodel::DataSource.
Definition at line 226 of file DB.hxx.
item_iter() [1/2]
std::unique_ptr< nodel::DataSource::ItemIterator > nodel::kvdb::DB::item_iter () override virtual
Reimplemented from nodel::DataSource.
Definition at line 231 of file DB.hxx.
key_iter() [2/2]
std::unique_ptr< nodel::DataSource::KeyIterator > nodel::kvdb::DB::key_iter (const Slice & slice) override virtual
Reimplemented from nodel::DataSource.
Definition at line 236 of file DB.hxx.
value_iter() [2/2]
std::unique_ptr< nodel::DataSource::ValueIterator > nodel::kvdb::DB::value_iter (const Slice & slice) override virtual
Reimplemented from nodel::DataSource.
Definition at line 256 of file DB.hxx.
item_iter() [2/2]
std::unique_ptr< nodel::DataSource::ItemIterator > nodel::kvdb::DB::item_iter (const Slice & slice) override virtual
Reimplemented from nodel::DataSource.
Definition at line 276 of file DB.hxx.
The documentation for this class was generated from the following file:
nodel/kvdb/DB.hxx